-- alter table cliente drop column i_idade_cliente;

/*
Tipos de relacionamento em um diagrama

Zero ou um (OO)
Um (|)
Um e somente um (||)
Muitos (E)
Zero ou muitos (OE)
Um ou muitos (|E)

indicam quantos registros iguais o campo relacionado pode ter na tabela

*/

-- MySQL Script generated by MySQL Workbench
-- Sat Jan  4 15:42:08 2025
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='ONLY_FULL_GROUP_BY,STRICT_TRANS_TABLES,NO_ZERO_IN_DATE,NO_ZERO_DATE,ERROR_FOR_DIVISION_BY_ZERO,NO_ENGINE_SUBSTITUTION';

-- -----------------------------------------------------
-- Schema cfbcursos
-- -----------------------------------------------------

-- -----------------------------------------------------
-- Schema cfbcursos
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `cfbcursos` DEFAULT CHARACTER SET utf8mb4 COLLATE utf8mb4_0900_ai_ci ;
USE `cfbcursos` ;

-- -----------------------------------------------------
-- Table `cfbcursos`.`tipocliente`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `cfbcursos`.`tipocliente` (
  `i_tipocliente_tipocliente` INT NOT NULL,
  `s_dsctipocliente_tipocliente` VARCHAR(100) NOT NULL,
  PRIMARY KEY (`i_tipocliente_tipocliente`))
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8mb4
COLLATE = utf8mb4_0900_ai_ci;


-- -----------------------------------------------------
-- Table `cfbcursos`.`cliente`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `cfbcursos`.`cliente` (
  `i_cliente_cliente` INT NOT NULL AUTO_INCREMENT,
  `s_nomecli_cliente` VARCHAR(30) NULL DEFAULT NULL,
  `s_cpf_cliente` VARCHAR(50) NOT NULL,
  `d_nasc_cliente` DATETIME NULL DEFAULT NULL,
  `i_tipo_cliente` INT NOT NULL,
  PRIMARY KEY (`i_cliente_cliente`),
  INDEX `fk_tipocliente` (`i_tipo_cliente` ASC) VISIBLE,
  CONSTRAINT `fk_tipocliente`
    FOREIGN KEY (`i_tipo_cliente`)
    REFERENCES `cfbcursos`.`tipocliente` (`i_tipocliente_tipocliente`))
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8mb4
COLLATE = utf8mb4_0900_ai_ci;


-- -----------------------------------------------------
-- Table `cfbcursos`.`tipoclienteExemploDiagrama`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `cfbcursos`.`tipoclienteExemploDiagrama` (
  `i_tipocliente_tipocliente` INT NOT NULL,
  `s_dsctipocliente_tipocliente` VARCHAR(100) NOT NULL,
  PRIMARY KEY (`i_tipocliente_tipocliente`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `cfbcursos`.`clienteExemploDiagrama`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `cfbcursos`.`clienteExemploDiagrama` (
  `i_cliente_cliente` INT NOT NULL AUTO_INCREMENT,
  `s_nome_cliente` VARCHAR(50) NOT NULL,
  `s_cpf_cliente` VARCHAR(11) NULL,
  `t_nasc_cliente` DATETIME NOT NULL,
  `i_tipo_cliente` INT NULL,
  PRIMARY KEY (`i_cliente_cliente`),
  INDEX `fk_clienteExemploDiagrama_tipoclienteExemploDiagrama1_idx` (`i_tipo_cliente` ASC) VISIBLE,
  CONSTRAINT `fk_clienteExemploDiagrama_tipoclienteExemploDiagrama1`
    FOREIGN KEY (`i_tipo_cliente`)
    REFERENCES `cfbcursos`.`tipoclienteExemploDiagrama` (`i_tipocliente_tipocliente`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;

DROP TABLE clienteexemplodiagrama;
DROP TABLE tipoclienteexemplodiagrama;